### ISSUE TITLE
2015的wwdc app里某些已经有了哦

### ISSUE THREAD

**Issue by gakaki** [qiaoxueshi/WWDC_2015_Video_Subtitle#1]
例如keynote

**Comment by eplt** [comment]
I have moved them all to https://github.com/eplt/WWDC-Video-Subtitles there are 40 sessions with SRTs already.

**Comment by XueshiQiao** [comment]
@gakaki 多谢提醒 我稍后会提交上

**Comment by XueshiQiao** [comment]
@eplt 👍

**Comment by XueshiQiao** [comment]
@gakaki @eplt  已经加上首批的40个字幕文件

**Comment by jiehu5114** [comment]
话说 这个字幕文字怎么用？

**Comment by XueshiQiao** [comment]
@jiehu5114 一般的播放器比如Mplayer,VLC都支持字幕
